name: CI/CD 

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_SECRET_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          ssh -o StrictHostKeyChecking=no -i deploy_key.pem ubuntu@$SERVER_IP <<EOF
            cd "/home/ubuntu/ship_route_efficiency_analysis"
            git pull
            npm install
            tmux kill-session -t mysession || true
            tmux new -d -s mysession 'npm start'
          EOF
